version: '3'
services:
  redis:
    build: 
      context: .
    restart: always
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
      - 6380:8000
    environment:
      TZ: "Asia/Kolkata"
